import { useEffect,useRef,useState } from 'react';
import { useGetAccount } from '@multiversx/sdk-dapp/out/react/account/useGetAccount';
import { UnlockPanelManager } from '@multiversx/sdk-dapp/out/managers/UnlockPanelManager';
import { ProviderFactory } from '@multiversx/sdk-dapp/out/providers/ProviderFactory';
import { ProviderTypeEnum } from '@multiversx/sdk-dapp/out/providers/types/providerFactory.types';
import { atomic,human } from '../bonez-swap/validation.js';
import { getJson } from '../bonez-swap/transactions.js';
import { liquidityQuote,LP,PAIR } from './validation.js';
import { fetchPool,fetchLiquidityBalances,prepareLiquidity,submitLiquidity } from './transactions.js';
import '../bonez-swap/swap.css';
import './liquidity.css';
const compact=(raw,decimals)=>{const [whole,part='']=human(raw,decimals).split('.');if(BigInt(raw)>0n&&whole==='0'&&!/[1-9]/.test(part.slice(0,4)))return '<0.0001';return whole+'.'+part.slice(0,4).padEnd(4,'0');};
export default function BonezLiquidity({onBusyChange}){
 const account=useGetAccount(),anchor=useRef(null),lock=useRef(false);
 const [pool,setPool]=useState(null),[balances,setBalances]=useState(null),[amount,setAmount]=useState('1000'),[slippage,setSlippage]=useState(50),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[overlay,setOverlay]=useState(false),[sent,setSent]=useState(null),[status,setStatus]=useState('Loading the verified BONEZ pool…'),[confirmed,setConfirmed]=useState(false);
 useEffect(()=>{let active=true;fetchPool().then(p=>{if(active){setPool(p);setStatus('Pool ready. Choose your BONEZ deposit.');}}).catch(e=>{if(active)setStatus(e.message);});return()=>{active=false};},[]);
 useEffect(()=>{setReview(null);setBalances(null);let active=true;if(account.address)fetchLiquidityBalances(account.address).then(b=>{if(active)setBalances(b);}).catch(()=>{if(active)setStatus('Could not load balances. Reconnect your wallet and try again.');});return()=>{active=false};},[account.address,confirmed]);
 useEffect(()=>{onBusyChange?.(busy||overlay);},[busy,overlay,onBusyChange]);
 useEffect(()=>{if(!review||busy)return;const timer=setTimeout(()=>{setReview(null);setStatus('Liquidity review expired. Review again for fresh pool checks.');},Math.max(0,review.created+60000-Date.now()));return()=>clearTimeout(timer);},[review,busy]);
 useEffect(()=>{if(!sent?.hash)return;let active=true,timer;async function poll(){try{const tx=await getJson(`https://api.multiversx.com/transactions/${sent.hash}`);if(!active)return;if(tx.status==='success'){setConfirmed(true);setStatus('Liquidity deposit confirmed. Check your LP balance and transaction details.');return;}if(['fail','invalid'].includes(tx.status)){setStatus('The deposit failed. Check transaction details before trying again.');return;}}catch{/* Indexing may lag. */}if(active)timer=setTimeout(poll,6000);}poll();return()=>{active=false;clearTimeout(timer);};},[sent]);
 let terms=null;try{if(pool)terms=liquidityQuote(pool,atomic(amount.trim(),6),slippage);}catch{/* Invalid inputs are explained when the user reviews. */}
 function change(){setReview(null);setSent(null);setConfirmed(false);}
 async function connect(){if(lock.current)return;if(!window.matchMedia('(max-width: 700px)').matches){void UnlockPanelManager.getInstance().openUnlockPanel();return;}lock.current=true;setBusy(true);setOverlay(true);try{const provider=await ProviderFactory.create({type:ProviderTypeEnum.walletConnect,anchor:anchor.current});await provider.login();setStatus('Wallet connected. Review your liquidity deposit.');}catch(e){setStatus(e.message||'Connection cancelled.');}finally{anchor.current?.replaceChildren();setOverlay(false);setBusy(false);lock.current=false;}}
 async function refresh(){if(lock.current)return;lock.current=true;setBusy(true);change();try{setPool(await fetchPool());if(account.address)setBalances(await fetchLiquidityBalances(account.address));setStatus('Pool and balances refreshed.');}catch(e){setPool(null);setStatus(e.message);}finally{setBusy(false);lock.current=false;}}
 async function prepare(){if(lock.current)return;lock.current=true;setBusy(true);setStatus('Checking both balances, pool ratio, and deposit simulation…');try{const result=await prepareLiquidity(pool,atomic(amount.trim(),6),slippage);setReview(result);setStatus('Review the two deposits, then approve in your wallet.');}catch(e){setReview(null);setStatus(e.message);}finally{setBusy(false);lock.current=false;}}
 async function sign(){if(lock.current||!review)return;lock.current=true;setBusy(true);setStatus('Approve the liquidity deposit in your wallet. Open xPortal manually if needed.');try{const result=await submitLiquidity(review,setStatus);setSent(result);setReview(null);setStatus(result.hash?'Deposit sent. Waiting for network confirmation…':'Deposit submitted. Check your wallet history.');}catch(e){setReview(null);setStatus(e.message);}finally{setBusy(false);lock.current=false;}}
 return <div className="bonez-page bonez-embedded liquidity-page"><header><button className="wallet-button" disabled={busy} onClick={account.address?refresh:connect}>{account.address?account.address.slice(0,7)+'…'+account.address.slice(-4)+' · Refresh':'Connect wallet'}</button></header><main><section className="swap-card"><div className="card-heading"><div><div className="eyebrow">FUEL THE BONEZ POOL</div><h2>Add liquidity</h2></div><span className="network"><i/> Mainnet</span></div><div className="wallet-note">BONEZ + WEGLD → LP tokens<br/><span>Deposit both tokens at the pool ratio. Any unused amounts are returned by the pair contract.</span></div>
 <div className="amount-box"><label htmlFor="liquidity-bonez">You deposit BONEZ</label><div className="amount-row"><input id="liquidity-bonez" inputMode="decimal" autoComplete="off" value={amount} disabled={busy} onChange={e=>{change();setAmount(e.target.value);}}/><span className="token"><img src="/images/cryptopittz-bonez-transparent.png" alt=""/>BONEZ</span></div><small>{balances?'Balance: '+compact(balances.bonez,6):'Connect to see your balance'}</small></div>
 <div className="liquidity-plus">+</div><div className="amount-box receive"><label>Matching WEGLD <span>estimated</span></label><div className="amount-row"><output title={terms?human(terms.second,18):undefined}>{terms?compact(terms.second,18):'—'}</output><span className="token">WEGLD</span></div><small>{balances?'Balance: '+compact(balances.wegld,18):'Calculated from live pool reserves'}</small></div>
 <div className="settings"><label htmlFor="liquidity-slippage">Slippage tolerance</label><select id="liquidity-slippage" value={slippage} disabled={busy} onChange={e=>{change();setSlippage(Number(e.target.value));}}><option value={50}>0.5%</option><option value={100}>1%</option><option value={200}>2%</option></select></div>
 <div className="liquidity-estimate"><span>Estimated LP received</span><strong>{terms?human(terms.estimatedLp,18):'—'}</strong><small>{LP}</small>{balances&&<small>Your LP balance: {human(balances.lp,18)}</small>}</div>
 <p className="liquidity-help">Use WEGLD, not native EGLD, for this deposit. Keep EGLD for network fees. LP tokens represent a share of the pool; returns are not fixed. Token price changes can cause impermanent loss.</p>
 {!review&&!sent&&<button className="gold-button" disabled={busy||!pool} onClick={account.address?prepare:connect}>{busy?'Please wait…':account.address?'Review liquidity deposit':'Connect wallet to add liquidity'}<span>→</span></button>}
 {!pool&&<button className="gold-button" disabled={busy} onClick={refresh}>Retry pool lookup →</button>}
 {review&&<div className="swap-review"><h3>Confirm your liquidity deposit</h3><p>Send up to <strong>{human(review.terms.first,6)} BONEZ</strong> and <strong>{human(review.terms.second,18)} WEGLD</strong>.</p><p>Minimum used by the pool: <strong>{human(review.terms.minFirst,6)} BONEZ</strong> and <strong>{human(review.terms.minSecond,18)} WEGLD</strong>.</p><p>Maximum network fee: <strong>{human(review.feeCap,18)} EGLD</strong></p>{review.guardian&&<p>Complete your guardian approval in the wallet.</p>}<small>The LP amount is an estimate. Fees apply even if the transaction fails.</small><button className="gold-button swap-action" disabled={busy} onClick={sign}>Approve in wallet →</button><button className="cancel-review" disabled={busy} onClick={()=>setReview(null)}>Back</button></div>}
 <p id="status" role="status" aria-live="polite">{status}</p>{sent?.hash&&<a className="transaction-link" href={'https://explorer.multiversx.com/transactions/'+sent.hash} target="_blank" rel="noreferrer">{confirmed?'Deposit confirmed':'View deposit transaction'} ↗</a>}
 <div className="card-foot">Verified BONEZ / WEGLD pair<a className="liquidity-pair-link" href={'https://explorer.multiversx.com/accounts/'+PAIR} target="_blank" rel="noreferrer">View pool contract ↗</a><p>LP tokens are separate from game Bonez. Manage withdrawals on xExchange.</p></div></section></main><div className={overlay?'swap-wallet-overlay':'swap-wallet-hidden'} role={overlay?'dialog':undefined} aria-modal={overlay||undefined} aria-label="Connect xPortal">{overlay&&<button onClick={()=>{setOverlay(false);anchor.current?.replaceChildren();}}>Close</button>}<div ref={anchor}/></div></div>;
}
