import { useEffect,useRef,useState } from 'react';
import { useGetAccount } from '@multiversx/sdk-dapp/out/react/account/useGetAccount';
import { UnlockPanelManager } from '@multiversx/sdk-dapp/out/managers/UnlockPanelManager';
import { ProviderFactory } from '@multiversx/sdk-dapp/out/providers/ProviderFactory';
import { ProviderTypeEnum } from '@multiversx/sdk-dapp/out/providers/types/providerFactory.types';
import { atomic,human } from '../bonez-swap/validation.js';
import { getJson } from '../bonez-swap/transactions.js';
import { CONTRACT } from './validation.js';
import { fetchStaking,fetchStakingBalances,prepareStaking,submitStaking } from './transactions.js';
import '../bonez-swap/swap.css';
import '../bonez-liquidity/liquidity.css';
import './staking.css';
const compact=(raw,decimals)=>{const [whole,part='']=human(raw,decimals).split('.');if(BigInt(raw)>0n&&whole==='0'&&!/[1-9]/.test(part.slice(0,4)))return '<0.0001';return whole+'.'+part.slice(0,4).padEnd(4,'0');};
const labels={stake:'Stake BONEZ',unstake:'Unstake BONEZ',claim:'Claim rewards',withdraw:'Withdraw unlocked BONEZ'};
export default function BonezStaking({onBusyChange}){
 const account=useGetAccount(),anchor=useRef(null),lock=useRef(false);
 const [pool,setPool]=useState(null),[balances,setBalances]=useState(null),[amount,setAmount]=useState('1000'),[action,setAction]=useState('stake'),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[overlay,setOverlay]=useState(false),[sent,setSent]=useState(null),[status,setStatus]=useState('Loading BONEZ staking…'),[confirmed,setConfirmed]=useState(false),[settled,setSettled]=useState(false),[refreshTick,setRefreshTick]=useState(0);
 useEffect(()=>{let active=true;setPool(null);setBalances(null);setReview(null);setSent(null);setConfirmed(false);setSettled(false);
  Promise.all([fetchStaking(account.address),account.address?fetchStakingBalances(account.address):Promise.resolve(null)]).then(([p,b])=>{if(active){setPool(p);setBalances(b);setStatus(p.paused?'OneDEX has paused this pool.':'Pool ready. You earn, we burn!');}}).catch(e=>{if(active)setStatus(e.message);});return()=>{active=false};
 },[account.address]);
 useEffect(()=>{if(!refreshTick||!account.address)return;let active=true;Promise.all([fetchStaking(account.address),fetchStakingBalances(account.address)]).then(([p,b])=>{if(active){setPool(p);setBalances(b);}}).catch(()=>{if(active)setStatus('Transaction confirmed. Refresh to reload your staking position.');});return()=>{active=false};},[refreshTick,account.address]);
 useEffect(()=>{onBusyChange?.(busy||overlay);},[busy,overlay,onBusyChange]);
 useEffect(()=>{if(!review||busy)return;const timer=setTimeout(()=>{setReview(null);setStatus('Review expired. Review again for fresh checks.');},Math.max(0,review.created+60000-Date.now()));return()=>clearTimeout(timer);},[review,busy]);
 useEffect(()=>{if(!sent?.hash)return;let active=true,timer;async function poll(){try{const tx=await getJson(`https://api.multiversx.com/transactions/${sent.hash}`);if(!active)return;if(tx.status==='success'){setConfirmed(true);setSettled(true);setRefreshTick(n=>n+1);setStatus('Staking transaction confirmed. Your position is refreshing.');return;}if(['fail','invalid'].includes(tx.status)){setSettled(true);setStatus('Transaction failed. Check transaction details before trying again.');return;}}catch{/* Indexing may lag. */}if(active)timer=setTimeout(poll,6000);}poll();return()=>{active=false;clearTimeout(timer);};},[sent]);
 function change(){setReview(null);setSent(null);setConfirmed(false);setSettled(false);}
 async function connect(){if(lock.current)return;if(!window.matchMedia('(max-width: 700px)').matches){void UnlockPanelManager.getInstance().openUnlockPanel();return;}lock.current=true;setBusy(true);setOverlay(true);try{const provider=await ProviderFactory.create({type:ProviderTypeEnum.walletConnect,anchor:anchor.current});await provider.login();setStatus('Wallet connected. Review your staking action.');}catch(e){setStatus(e.message||'Connection cancelled.');}finally{anchor.current?.replaceChildren();setOverlay(false);setBusy(false);lock.current=false;}}

 async function refresh(){if(lock.current)return;lock.current=true;setBusy(true);change();try{const [p,b]=await Promise.all([fetchStaking(account.address),account.address?fetchStakingBalances(account.address):Promise.resolve(null)]);setPool(p);setBalances(b);setStatus('Pool and wallet position refreshed.');}catch(e){setPool(null);setStatus(e.message);}finally{setBusy(false);lock.current=false;}}
 async function prepare(){if(lock.current)return;lock.current=true;setBusy(true);setStatus('Verifying your staking position and simulating the transaction…');try{setReview(await prepareStaking(action,['stake','unstake'].includes(action)?atomic(amount.trim(),6):'0'));setStatus('Review the action, then approve in your wallet.');}catch(e){setReview(null);setStatus(e.message);}finally{setBusy(false);lock.current=false;}}
 async function sign(){if(lock.current||!review)return;lock.current=true;setBusy(true);setStatus('Approve in your wallet. Open xPortal manually if needed.');try{const result=await submitStaking(review);setSent(result);setReview(null);setStatus(result.hash?'Transaction sent. Waiting for confirmation…':'Transaction submitted. Check your wallet history.');}catch(e){setReview(null);setStatus(e.message);}finally{setBusy(false);lock.current=false;}}
 return <div className="bonez-page bonez-embedded staking-page"><header><button className="wallet-button" disabled={busy} onClick={account.address?refresh:connect}>{account.address?account.address.slice(0,7)+'…'+account.address.slice(-4)+' · Refresh':'Connect wallet'}</button></header><main><section className="swap-card"><div className="card-heading"><div><div className="eyebrow">YOU EARN, WE BURN!</div><h2>BONEZ Staking</h2></div><span className="network"><i/> Mainnet</span></div>
 <div className="wallet-note">Put your BONEZ to work.<br/><span>Stake BONEZ on OneDEX and claim rewards in BONEZ.</span></div>
 <div className="staking-position"><div><span>Your staked BONEZ</span><strong title={pool?.user?human(pool.user.staked,6):undefined}>{pool?.user?compact(pool.user.staked,6):'—'}</strong></div><div><span>Claimable BONEZ</span><strong title={pool?.user?human(pool.user.rewards,6):undefined}>{pool?.user?compact(pool.user.rewards,6):'—'}</strong></div></div>
 <div className="staking-actions" role="group" aria-label="Choose staking action">{Object.entries(labels).filter(([id])=>id!=='withdraw'||pool?.unbondEpochs>0||pool?.user?.pendingCount>0).map(([id,label])=><button key={id} className={action===id?'active':''} aria-pressed={action===id} disabled={busy} onClick={()=>{change();setAction(id);}}>{label}</button>)}</div>
 {['stake','unstake'].includes(action)&&<div className="amount-box"><label htmlFor="staking-amount">{action==='stake'?'You stake':'You unstake'}</label><div className="amount-row"><input id="staking-amount" inputMode="decimal" autoComplete="off" value={amount} disabled={busy} onChange={e=>{change();setAmount(e.target.value);}}/><span className="token"><img src="/images/cryptopittz-bonez-transparent.png" alt=""/>BONEZ</span></div><small>{balances?'Wallet balance: '+compact(balances.bonez,6)+' BONEZ':'Connect to see your balance'}</small></div>}
 {action==='claim'&&<p className="staking-action-note">Claim your accrued rewards to your connected wallet. The contract calculates the final reward when the transaction executes.</p>}
 {action==='withdraw'&&<p className="staking-action-note">{pool?.user?pool.user.pendingCount+' pending withdrawal entries. ':''}Withdraw entries that have finished unbonding. Simulation checks whether a withdrawal is available.</p>}
 <div className="liquidity-estimate"><span>Current unbonding period</span><strong>{pool?pool.unbondEpochs+' epochs':'—'}</strong><small>{pool?.unbondEpochs===0?'The current pool returns unstaked BONEZ directly.':'Unstaking starts a waiting period. Withdraw unlocked BONEZ after it ends.'}</small><span>Total BONEZ staked</span><strong>{pool?compact(pool.totalStaked,6):'—'}</strong></div>
 <p className="liquidity-help">Rewards depend on the pool’s terms and available funding. Keep EGLD for network fees. Staking uses real BONEZ tokens, separate from game Bonez.</p>
 {!review&&!sent&&<button className="gold-button" disabled={busy||!pool||pool.paused} onClick={account.address?prepare:connect}>{busy?'Please wait…':account.address?'Review '+labels[action].toLowerCase():'Connect wallet to stake'}<span>→</span></button>}
 {!pool&&<button className="gold-button" disabled={busy} onClick={refresh}>Retry staking lookup →</button>}
 {review&&<div className="swap-review"><h3>{labels[review.action]}</h3>{['stake','unstake'].includes(review.action)&&<p>Amount: <strong>{human(review.amount,6)} BONEZ</strong></p>}<p>OneDEX · BONEZ pool 49</p>{review.action==='unstake'&&<p>Current unbonding: <strong>{review.unbondEpochs} epochs</strong></p>}<p>Maximum network fee: <strong>{human(review.feeCap,18)} EGLD</strong></p>{review.guardian&&<p>Complete guardian approval in your wallet.</p>}<small>Fees apply even if the transaction fails. Rewards and pool terms can change.</small><button className="gold-button swap-action" disabled={busy} onClick={sign}>Approve in wallet →</button><button className="cancel-review" disabled={busy} onClick={()=>setReview(null)}>Back</button></div>}
 <p id="staking-status" role="status" aria-live="polite">{status}</p>{sent?.hash&&<a className="transaction-link" href={'https://explorer.multiversx.com/transactions/'+sent.hash} target="_blank" rel="noreferrer">{confirmed?'Transaction confirmed':'View staking transaction'} ↗</a>}{sent&&<button className="cancel-review" disabled={busy||(!settled&&!!sent.hash)} onClick={refresh}>Refresh position</button>}
 <div className="card-foot">OneDEX · BONEZ pool 49<a className="liquidity-pair-link" href={'https://explorer.multiversx.com/accounts/'+CONTRACT} target="_blank" rel="noreferrer">View staking contract ↗</a><p>You earn, we burn!</p></div></section></main><div className={overlay?'swap-wallet-overlay':'swap-wallet-hidden'} role={overlay?'dialog':undefined} aria-modal={overlay||undefined} aria-label="Connect xPortal">{overlay&&<button onClick={()=>{setOverlay(false);anchor.current?.replaceChildren();}}>Close</button>}<div ref={anchor}/></div></div>;
}
